x-airflow-common: &airflow-common
  image: apache/airflow:2.9.3
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    PYTHONPATH: /opt/airflow
    CREDIT_DB_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    _PIP_ADDITIONAL_REQUIREMENTS: "scikit-learn==1.5.1 pyarrow==16.1.0"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./data:/opt/airflow/data
    - /data_lids/home/gabrielseabra/credit-score-analysis/.docker/airflow-logs:/opt/airflow/logs
    - /data_lids/home/gabrielseabra/credit-score-analysis/.docker/tmp:/tmp
  depends_on:
    postgres:
      condition: service_healthy
  networks:
    - credit-net

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - /data_lids/home/gabrielseabra/credit-score-analysis/.docker/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - credit-net

  airflow-init:
    <<: *airflow-common
    command:
      - bash
      - -c
      - >-
        airflow db migrate &&
        airflow users create
        --username admin
        --password admin
        --firstname Admin
        --lastname User
        --role Admin
        --email admin@example.com
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: unless-stopped

networks:
  credit-net:
    driver: bridge
